### ISSUE TITLE
where did you get the updated url?

### ISSUE THREAD

**Issue by mahadshahib** [wizard-gg/RadioJavan-Downloader#2]
salam dadash az koja url jadid gir miad k update konim?

**Comment by wizard-gg** [comment]
> salam dadash az koja url jadid gir miad k update konim?

Salam URL az site asli update mishe (url asli baraye ma ye URL bdone filter e!)
MerC az etela resani Service Live va Git update shod.

**Comment by mahadshahib** [comment]
مرسی یکم دیر بود ولی دمت گرم خودم از اپ مک او اس رادیوجوان گرفتم ادرس جدیدشو اپدیت زدم
